# Homebrew Formula for Halo
# Auto-generated by GitHub Actions

class Halo < Formula
  desc "Local DNS and SSL management tool for development"
  homepage "https://github.com/freedomforeversolar/halo"
  version "1.0.2"
  license "MIT"

  # Different URLs for different architectures
  on_arm do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.2/halo-darwin-arm64"
    sha256 "9f06c33cb522955e16a45aff04f232d3764f8e708b950e5a8dd851aa9a55b2e6"
  end

  on_intel do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.2/halo-darwin-x64"
    sha256 "81b6024606e986fcfb8b144528bb13cea2b713b98d688aeddfbb8b7d7f926550"
  end

  depends_on "caddy"
  depends_on "dnsmasq"

  def install
    # The downloaded file is already a compiled executable
    bin.install "halo-darwin-#{Hardware::CPU.arch}" => "halo"
  end

  def caveats
    <<~EOS
      🔵 Halo has been installed!
      
      To complete setup, run:
        halo setup

      This will configure DNS and SSL certificates for local development.
      
      Quick start:
        halo setup
        halo add portal.myapp localhost:3000
        open https://portal.myapp
    EOS
  end

  test do
    assert_match "1.0.2", shell_output("#{bin}/halo --version")
  end
end
