# Homebrew Formula for Halo
# Auto-generated by GitHub Actions

class Halo < Formula
  desc "Local DNS and SSL management tool for development"
  homepage "https://github.com/freedomforeversolar/halo"
  version "1.0.3"
  license "MIT"

  # Different URLs for different architectures
  on_arm do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.3/halo-darwin-arm64"
    sha256 "2587d9227bdc3992757fd4e15240190705aa62b2da0c69b4776fe486c8faf7bf"
  end

  on_intel do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.3/halo-darwin-x64"
    sha256 "731b32b31eb0e9fa81d94eb2101c37af597e07213c2954f8891c0780159ecdbc"
  end

  depends_on "caddy"
  depends_on "dnsmasq"

  def install
    # The downloaded file is already a compiled executable
    bin.install "halo-darwin-#{Hardware::CPU.arch}" => "halo"
  end

  def caveats
    <<~EOS
      🔵 Halo has been installed!
      
      To complete setup, run:
        halo setup

      This will configure DNS and SSL certificates for local development.
      
      Quick start:
        halo setup
        halo add portal.myapp localhost:3000
        open https://portal.myapp
    EOS
  end

  test do
    assert_match "1.0.3", shell_output("#{bin}/halo --version")
  end
end
