# Homebrew Formula for Halo
# Auto-generated by GitHub Actions

class Halo < Formula
  desc "Local DNS and SSL management tool for development"
  homepage "https://github.com/freedomforeversolar/halo"
  version "1.0.7"
  license "MIT"

  # Different URLs for different architectures
  on_arm do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.7/halo-darwin-arm64"
    sha256 "dfed12a100650f87f7c113413d89c21b872fb5c8db92dd84fe4ab3e81add2c1a"
  end

  on_intel do
    url "https://github.com/freedomforeversolar/halo/releases/download/v1.0.7/halo-darwin-x64"
    sha256 "9816361d4f5261d07b05d7267a3745f4f17c96a60b0c3d4b2c0beb4e9c82ae60"
  end

  depends_on "caddy"
  depends_on "dnsmasq"

  def install
    # The downloaded file is already a compiled executable
    bin.install "halo-darwin-#{Hardware::CPU.arch}" => "halo"
  end

  def caveats
    <<~EOS
      🔵 Halo has been installed!
      
      To complete setup, run:
        halo setup

      This will configure DNS and SSL certificates for local development.
      
      Quick start:
        halo setup
        halo add portal.myapp localhost:3000
        open https://portal.myapp
    EOS
  end

  test do
    assert_match "1.0.7", shell_output("#{bin}/halo --version")
  end
end
