# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramp < Formula
  desc "CLI tool for managing multi-repository development workflows using git worktrees"
  homepage "https://github.com/FreedomForeverSolar/ramp"
  version "1.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.3.5/ramp_1.3.5_Darwin_x86_64.tar.gz"
      sha256 "faa20b43b0f197ed3e14dc145aaad68d3b6f8a053954da86cc14ad47c91933f4"

      def install
        bin.install "ramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.3.5/ramp_1.3.5_Darwin_arm64.tar.gz"
      sha256 "46a6fdc85aae65a16c0d6d523aba2a29d2d218909f90761f0f9b0a7eeec3346a"

      def install
        bin.install "ramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.3.5/ramp_1.3.5_Linux_x86_64.tar.gz"
      sha256 "667ae8b998ea4af6e8ab5e6e12a25046cf1c4a7ffd3899ec9091895e223e52e7"
      def install
        bin.install "ramp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.3.5/ramp_1.3.5_Linux_arm64.tar.gz"
      sha256 "081386e5df41090e386cd00dabf0f1e2ff038a2214557d24ff65af78115b3529"
      def install
        bin.install "ramp"
      end
    end
  end

  test do
    system "#{bin}/ramp", "--help"
  end
end
