# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramp < Formula
  desc "CLI tool for managing multi-repository development workflows using git worktrees"
  homepage "https://github.com/FreedomForeverSolar/ramp"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.6.1/ramp_1.6.1_Darwin_x86_64.tar.gz"
      sha256 "c613279f9b52ca82d0a07fc45a98a76dd5f46f25cc5701c5276af79c97f0cb07"

      def install
        bin.install "ramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.6.1/ramp_1.6.1_Darwin_arm64.tar.gz"
      sha256 "3779be4c8a24d9df993513170b8777efb7a19ba536f4a16d72108ab5db36e3e7"

      def install
        bin.install "ramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.6.1/ramp_1.6.1_Linux_x86_64.tar.gz"
      sha256 "6b76fe5f3effc3085e1a200ca4e68df2eae68cae9e2eb066ee3b823284095c4e"
      def install
        bin.install "ramp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FreedomForeverSolar/ramp/releases/download/v1.6.1/ramp_1.6.1_Linux_arm64.tar.gz"
      sha256 "724a39aae1867a8cc269b9477e68852e2f00f4c34dd5ef34a19d49e5368070b2"
      def install
        bin.install "ramp"
      end
    end
  end

  test do
    system "#{bin}/ramp", "--help"
  end
end
